Package initiation and init a Tez module
funkywork/yourbones pull request #1
Opened 2023-02-11 11:52 UTC by xvw

This is a join-work with @mspwn. 
- [ x ] Initialize the project (and fit with `Nightmare` organization)
- [ x ] Introduce a `Tez` module
- [ x ] Add tests for the corner cases of the `Tez` module.

2023-02-11 12:56 UTC, xhtmlboi requested changes
Very good start! 
I am still wary of including nanotez in the overall representation of tez. I understand that this is to easily describe the fees for bytes and for gas units but:

- while The Protocol is used to describe the maximum amount of mutez $(2^{63})-1$, by taking on board the nanotez we limit this number to $((2^{63})-1)/1000$
- the rule of rounding is trivial. We go down to the lowest floor.

So I'm not opposed to managing them in this way, but I'm not at all convinced that it's really useful.

2023-02-11 12:56 UTC, xhtmlboi commented on lib/common/tez.ml
> +  let ( <= ) x y = Int64.compare x y <= 0
I think this part should be tested, you can quickly make mistakes when manipulating the `compare` function.

2023-02-11 12:56 UTC, xhtmlboi commented on lib/common/tez.ml
> +;;
As the library embeds the `Nanotez`, it should go up to 9  ;)

2023-02-11 12:56 UTC, xhtmlboi commented on lib/common/tez.ml
> +    | _ -> None
Same here about the support of `Nanotez`.

2023-02-11 12:56 UTC, xhtmlboi commented on lib/common/tez.ml
> +  |> Result.map_error (fun _ -> `Tez_invalid_string_representation str)
Why this "error nromalization"?

2023-02-12 14:24 UTC, xvw commented on lib/common/tez.ml
> +  |> Result.map_error (fun _ -> `Tez_invalid_string_representation str)
In order to reject this kind of string : `123.-451` with the error `Tez_invalid_string_representation "123.-451"` and not with `Tez_negative_amount -451L` which is more clear (imho).

2023-02-12 14:43 UTC, xvw commented on lib/common/tez.ml
> +  let ( <= ) x y = Int64.compare x y <= 0
Done

2023-02-12 14:53 UTC, xhtmlboi approved these changes
Thank you. I think it's better (and we can think about nanotez when we implement the operation estimates). I'll leave it to @gr-im to merge if he agrees and add that I appreciate these tiny, easy-to-read PRs!

2023-02-12 19:58 UTC, gr-im approved these changes

2023-02-12 19:59 UTC, merged